### ISSUE TITLE
Removing <div> from value

### ISSUE THREAD

**Issue by friksa** [AddJam/ember-content-editable#3]
When editing the value and pressing enter, you get a <div> added to the value.  It would be nice to have that removed before updating the value.

It would be nice to specify that it should be a text only value vs html and then convert all <br> tags to \r\n

This will make the component more versatile if it can be used as a text only or html editor.

**Comment by chrissloey** [comment]
Looking into the best way of handling this right now.

**Comment by chrissloey** [comment]
Ok so previously the component was just using jquery `.text()` on the element to get a value. I'm about to release 0.3 which includes an `isText` property that can be passed to the component.

If isText is false, it will use jquery `.html()` and then call htmlSafe() on that to prevent `&nbsp;` etc showing up in output.

If isText is true, it will use `innerText` or `textContent` instead of `.text()` in order to preserve newlines.

I think the bigger issue here is what you references regarding extra `<div>`s. I looked into it and this sort of behaviour is a bug, mostly in webkit. Other tags like spans, font tags etc have been reported too. See [this SO thread](http://stackoverflow.com/questions/18383803/browser-automatically-inserts-unwanted-code-on-enter-in-contenteditable-div) and [this blog post](http://www.neotericdesign.com/blog/2013/3/working-around-chrome-s-contenteditable-span-bug). I'm not sure it's possible for the component to tackle that under every situation.

Workarounds I've found include using `display: inline-block` on your contenteditable div, which results in no div tags being inserted.

Alternatively you can also pass in a function to the component as `stringInterpolator=myInterpolator`, when the value is changed it gets passed to the interpolator and the return value is then used. So you could implement a function `myInterpolator(value) { /*some code*/ return valueWithNoDivs; }`.

**Comment by friksa** [comment]
isText=true works great and no div present when used.   the inline-block workaround works great when isText=false.

**Comment by chrissloey** [comment]
Great! :)
